Gruntfile.js, README.md, public/index.html
:koala:
/cc @zendesk/quokka
- None
=> Improve examples

doc/source/sdk/v1/iframes_in_apps.md
:bread:
* None (only changes docs)
=> Update CDN links to point to 1.0

README.md
:v:
Removed latest from the readme.
* JIRA:
=> no more latest in the README

lib/client.js
:v:
Revert docs being live
* JIRA:
=> [AF-311] Revert docs that are now live

spec/client_spec.js
:v:
Rewrote small tests for Stefan
* JIRA:
=> rewrote little test

lib/client.js, spec/client_spec.js
:v:
Who changed this line!?!?! Oh wait I did. oops. use pre increment!
* JIRA:
=> pre increment!

Gruntfile.js, lib/client.js, lib/utils.js, spec/client_spec.js, spec/utils_spec.js
✌️
Implementation of v2 save hook in the SDK.
Relies on a PR in ZAF, zendesk/zendesk_app_framework#573
* ZAF PR:  zendesk/zendesk_app_framework#573
* JIRA: https://zendesk.atlassian.net/browse/AF-292
* [low] The triggering of custom events within the iframe might be adversely affected by the special-casing of ZAF events that expect a reply.
=> [AF-292] As an App Developer, I want to register a save hook from my IFO app

test_app/manifest.json
:v:
frameworkVersion "2.0" for iframe apps
* JIRA: https://zendesk.atlassian.net/browse/AF-371
* JIRA:
=> [AF-371] framework version needs to be 2.0

lib/client.js, lib/index.js, spec/client_spec.js, testem.json
:v: 🚧 
See https://github.com/zendesk/zendesk_app_framework/pull/589
* JIRA: https://zendesk.atlassian.net/browse/AF-359
- ?
=> [AF-359] Add app instances API for v2

lib/client.js
=> Delete inline instance api documentation

lib/client.js, spec/client_spec.js
:v:
SDK will throw errors when doing single requests, but not in bulk requests.
Also we now have an errors object which the user can use to look at the errors.
* JIRA: 
* PR: https://github.com/zendesk/zendesk_app_framework/pull/588
=> Single requests error throw

lib/client.js, spec/client_spec.js
:v:
Added tests and tests and tests.
Reverted 1 breaking change: always return full result
* JIRA:
=> Return full results, and tests

lib/utils.js
:v:
So it's consistent with v1: https://github.com/zendesk/zendesk_app_framework/blob/master/lib/events/hook.js#L43
* [low] Could break v2 save hook
=> Save hook should resolve when return is omitted

lib/client.js
=> Better error message for `set`

lib/index.js
:v:
Support hash params for origin and app guid
* JIRA: https://zendesk.atlassian.net/browse/AF-488
* medium: handshake breaks, causing all v2 api calls to fail/error out
=> [AF-488] Support hash params for origin and app guid

lib/client.js, spec/client_spec.js
:v:
* [low] Could break apps using the instance API (closed beta only)
=> Throw an Error when an instanceGuid is not passed to instance API

CONTRIBUTING.md, DEPLOY.md, README.md
:v:
Add DEPLOY and move CONTRIBUTING from README to its own file for consistency.
=> Add DEPLOY and CONTRIBUTING

lib/client.js, lib/utils.js, spec/client_spec.js
:v:
Accept object in invoke!
* JIRA: https://zendesk.atlassian.net/browse/AF-785
=> [AF-785] accept object in invoke

.travis.yml, lib/client.js, lib/tracking.js, package-lock.json, package.json, spec/client_spec.js, spec/tracking_spec.js, testem.json
We will send tracking blips when a user hovers over an app for more than 200ms. This minimum time is to limit the number of blips generated in instances where a user might be wiggling the mouse around.
* JIRA: [As an agent, when I move my mouse out of a sidebar app, a blip should be sent to Hive
](https://zendesk.atlassian.net/browse/APPS-3792)
* [low] May generate as many as 5 per second per user
=> [APPS-3792] Mouse hover length tracking

lib/client.js, spec/client_spec.js, spec/index_spec.js
Reverts zendesk/zendesk_app_framework_sdk#59
=> Revert "Revert "Add a whitelist of origins""

lib/client.js, spec/client_spec.js
Add localhost to the whitelist
=> [AF-1075] Add localhost to the whitelist

lib/client.js, spec/client_spec.js
=> Fix regex (take 3)

README.md
=> Update Readme.MD to reflect webpack changes.

package.json, webpack.config.js
:v:
Update the Webpack config introduced in https://github.com/zendesk/zendesk_app_framework_sdk/pull/73 to ensure the minified version of `zaf_sdk.js` is also output. 
Low - Webpack fails to build.
=> Ensure minified file is output

package-lock.json, package.json
:v:
Updates `webpack-dev-server` from a version containing a high severity vulnerability.
* https://www.npmjs.com/advisories/725
* Low - Issues testing ZAF SDK locally with changes to dev server.
=> Update vulnerable webpack-dev-server version

.travis.yml, README.md
Set up Fossa open source scanning.
* https://zendesk.atlassian.net/browse/AF-1489
=> [AF-1489] Set up fossa open source scanning

lib/client.js, spec/client_spec.js
✌️
Low. This affects an informative check that currently displays an error in the console.
=> Allowlist Zendesk Sell domains

lib/client.js, spec/client_spec.js
Stop apps from loading from non-whitelisted domains
Also we unload the app from the DOM if the origin isnt whitelisted
=> [AF-1975] Clear iframe when origin isnt whitelisted

lib/client.js, spec/client_spec.js
Reverts zendesk/zendesk_app_framework_sdk#106
=> Revert "[AF-1975] Clear iframe when origin isnt whitelisted"

.travis.yml, package-lock.json, package.json
✌️
Restrict node engine to >12.10.0 for ZAFSDK
JIRA: https://zendesk.atlassian.net/browse/VEGEMITE-150
tbd
Low, should not alter the behaviour of ZAFSDK
=> [VEGEMITE-150] Bump to node 12

package-lock.json, package.json
Babel is not a code dependency, this needs to be moved to dev deps too to avoid snyk scanning this.
=> Move babel to dev deps

.github/PULL_REQUEST_TEMPLATE.md, DEPLOY.md
@zendesk/vegemite 
Adds a pull request template and adds a recovery section to DEPLOY.md.
This is part of ensuring that we have a rollback plan for any changes that we make to the zaf sdk.
* [VEG-367](https://zendesk.atlassian.net/browse/VEG-367)
=> [VEG-367] Add pull request template and add recovery section to DEPLOY.md

karma.conf.js, lib/client.js, lib/utils/idleState.ts, package-lock.json, package.json, spec/client_spec.js, spec/utils/idleState_spec.js, spec/utils/listeners_spec.js
JIRA: 🎫  [KOOK-1550](https://zendesk.atlassian.net/browse/KOOK-1550)
In order to resolve [KOOK-912](https://zendesk.atlassian.net/browse/KOOK-912) team kookaburra debugged to understand what may be the best solution on how to utilise the post message that` zaf_sdk` now sends to `lotus`.  It was realised that we do not need a timer in `zaf_sdk,` we only need the post message to send every time there is an event in an app.  Then `lotus` will handle any timer needed.  This  PR attempts to clean up the timer logic from `idleState.ts` and `client.js`.  The PR also adds` lodash debounce` to minimise the events to run once every 1000ms.  With these changes to the `zaf_sdk` Kookaburra can focus on listening for the post message in lotus to extend the session and fix the bug causing sessions to …
=> Kook-1550 Clean up timer logic 

karma.conf.js, lib/client.js, lib/utils.js, lib/utils/idleState.ts, package-lock.json, package.json, spec/client_spec.js, spec/utils/idleState_spec.js, spec/utils/listeners_spec.js
Reverts zendesk/zendesk_app_framework_sdk#170
🎫 [KOOK-1859](https://zendesk.atlassian.net/browse/KOOK-1859)
This is the re-introduction of PR #168  which was reverted due to [INCIDENT-1988](https://zendesk.atlassian.net/browse/INCIDENT-1988)
This PR aims to introduce a fix by
- removing Lodash from the `/lib/client` and` package.json`
- adding native Javascript debounce logic to `uitils.js` 
- Debounce works as expected. 
https://user-images.githubusercontent.com/59402195/182530105-a5a47d2d-5228-45c0-9ac6-61cb8c2cb5e5.mov
- Make sure [Zendesk Apps Framework regression tests](https://zendesk.atlassian.net/wiki/spaces/ENG/pages/641702848/DevQA+process+in+Vegemite#DevQAprocessinVegemite-regression-checks) are passing with this change.
NOTE: DevQA steps are to be …
=> Revert "Revert "Merge pull request #168 from zendesk/kookaburra/DEBUG_KOOK-1550""

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release.yml
:v:
Describe the original problem and the changes made on this PR.
- Add release action
- add patch label will bump patch version when merge
- add minor label will bump minor version when merge
- add major label will bump major version when merge
* Low: Ci change only
=> [VEG-1208] add release action

lib/client.js
:v:
It seems there is  memory leak issue in ZAFv2 framework `.request` method.
This is the replication code. (It simply makes API request every 10s on the same endpoint):
```
let client = ZAFClient.init(),
i = 0;
let getIt = function(){
client.request("/api/v2/views/360023653655/tickets.json").then(
()=>{i++},
()=>{i++}
);
};
client.on("app.registered", (appData)=>{
if (appData.context.location === "background"){
getIt();
setInterval(getIt, 10000);
}
});
```
Attached screenshot is the outcome. The `ZAFClient` built up with `request:X.done` and `request:X.fail` of the request, holding the API data forever.
This leads to memory built up (in the screenshot it was under 3 minutes)
10MB -> 15MB -> 20MB -> 40MB
* JIRA: https://zendesk.atlassian.net/browse/VEG-1906
- Make …
=> Clear handlers of request:X.done and request:X.fail of the request
