zendesk/zendesk_app_framework_sdk

doc/source/sdk/v1/iframes_in_apps.md, lib/client.js
:koala:
The docs included examples of listening to the `app.activated` event. This was confusing for app developers, because by the time the iframe is loaded the `app.activated` event has already fired. This PR changes examples to use `app.registered` instead, which is fired by the framework once the iframe is registered with the app.
/cc @zendesk/quokka
- None
=> Use app.registered instead of app.activated

lib/client.js
:v:
.parent instead of .top
* JIRA: 
- framwork sdk stops working because it can't connect anymore
=> window.parent instead of top

lib/utils.js, spec/utils_spec.js
:v:
Where a Save Hook handler was returning immediately, rather than a Promise, the rules governing Save Hook return values weren't being respected.
* [low] Save Hook allowing Ticket Save when not intended, or vice-versa
=> [BUG] Fixes an issue where Save Hook rules aren't being respect for synchronous return

.travis.yml, lib/client.js, spec/client_spec.js
:v:
Add subscriber count to iframe event handler events.
This allows the framework to know how many subscribers are listening inside the iframe, and when it's safe to bind/unbind.
* JIRA: 
* low: data attribute of event is unused
=> Add subscriber count to iframe event handler events

lib/client.js, spec/client_spec.js
:v:
✅  _Depends on https://github.com/zendesk/zendesk_app_framework/pull/622_
Add support for binding and triggering events across instances. This PR also changes the `instance` API to return a client rather than a promise that resolves with a client. See discussion [here](https://github.com/zendesk/zendesk_app_framework_sdk/pull/25/files#r71476024).
* JIRA: https://zendesk.atlassian.net/browse/AF-359
* [low] instances API may not work as intended.
=> [AF-359] Add support for binding and triggering events across instances

.travis.yml, Gruntfile.js, lib/client.js, package.json, spec/client_spec.js, testem.json
[postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) uses the [structured clone algo](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) which does not like sending error objects.
=> Send caught error responses when replying

lib/client.js, spec/client_spec.js
:v:
`postMessage` already wraps the second argument within `message` [here](https://github.com/zendesk/zendesk_app_framework_sdk/blob/master/lib/client.js#L272).
* [low] `trigger` API may pass data incorrectly
=> Stop double nesting message

lib/client.js
/cc @zendesk/vegemite 
Currently we have a very nice polyfill in the SDK. But all apps that include this SDK, still don't have this polyfill available, which means all apps will need to include their own polyfill. This seems very strange to me, and it would be nice if we can export the polyfill to window, so apps automatically don't need to worry about Promise polyfill.
Export Promise to window so v2 apps don't need to include their own Promise polypill.
I have tested this, and it works great!
=> Export Promise

lib/client.js, spec/client_spec.js
Relies on the ZAF work here https://github.com/zendesk/zendesk_app_framework/pull/769 to send tracking blips whenever someone clicks in an app.
:stop_sign: This should not be deployed until the corresponding ZAF PR above is deployed (apps won't break, but there'll be a lot of console errors as the `invoke` call fails to find a handler for `track`. :stop_sign: 
https://zendesk.atlassian.net/browse/APPS-3789
=> [APPS-3789] Setup event listeners for app tracking

lib/client.js, lib/tracking.js, spec/client_spec.js
`grunt-testem-mincer` is super out of date and relies on an old version of `testem`. This relies on an old version of `ws-pure`, which is forked from `ws` at the point where `ws` had a nasty bug (it would sometimes mysteriously throw out of range errors (https://github.com/websockets/ws/issues/778).
To avoid this bug I've just extracted all my code and stubbed it out in the test.
https://zendesk.atlassian.net/browse/APPS-3789
Risks:
none: just a test.
=> [APPS-3789] Refactor tracking code to dodge bug in grunt-testem-mincer

lib/index.js, lib/utils.js, spec/utils_spec.js
In jasmine we are trying to do fishy stuff to stub out the window.document.location.search, but instead we should be able to pass it to the init function so we can test this much easier!
=> optional queryString for init

lib/client.js, spec/client_spec.js, spec/index_spec.js
Any website can include zendesk_app_framework, embed one of our iframed app, and be able to sniff the events and data. This PR is adding a whitelist of domains to prevent this.
Reported Issue: https://support.zendesk.com/agent/tickets/3371584
@zendesk/vegemite 
Limitations: Since this is a front-end only fix, anyone can easily bypass this, we should think about adding nginx rules on the app assets to not be allowed to be iframed on any other domains.
=> Add a whitelist of origins

lib/client.js, spec/client_spec.js
I verified that our regex pattern for validating domains matches with the one's used by the [JIRA app](https://github.com/zendesk/jig/blob/master/config/initializers/charcoal.rb#L2).
Since, the jira app has been out in production for a long time and being used by thousands of customers, I think we should be confident and throw an error on any domain than does not match our regex pattern.
@zendesk/vegemite
=> Throw when domain is invalid

lib/client.js, spec/client_spec.js
Send the invalid domain error to Datadog instead of throwing. We can monitor this for a few days before we release the versions which throws, as throwing an error here(if done wrong) can we very high risk and can break a lot of apps.
Requires ZAF PR: https://github.com/zendesk/zendesk_app_framework/pull/788
@zendesk/vegemite
=> Instead of throw, send to DD

lib/client.js
@zendesk/vegemite 
Send an event to DD when a ZAF request times out.
LOW. Just adding a new metric to send to DD.
=> Send data to DD on timeout reject

package.json
✌️
Amends the `npm run-script bump` task added in https://github.com/zendesk/zendesk_app_framework_sdk/pull/78 to stay consistent with the legacy `grunt bump` task.
None - only updates the commit message.
=> Empty commit message for consistency with legacy Grunt bump task

lib/client.js, spec/client_spec.js
@zendesk/vegemite
Increase promise timeout to 10 seconds to allow more time for requests to resolve. It seems especially during initialisation 5 seconds may not be enough for requests to complete when many apps are loading at the same time.
ZD#4058685
- [low]  In case there's a legitimate reason for `postMessage` to never resolve it will take longer for the app to be able to handle the error.
=> Increase promise timeout to 10 seconds

webpack.config.js
`ZAFClient` should have a `init` function, not a `default` property that has a `init` function.
=> Fixed output of webpack

lib/client.js
:v:
Adds tags to the `sdk_request_timeout` event tracking to capture which APIs timed out. 
Related to https://github.com/zendesk/zendesk_app_framework/pull/823.
* JIRA: https://zendesk.atlassian.net/browse/AF-1476
* Low - Datadog tracking for `sdk_request_timeout` fails because of errors in tag strings.
=> [AF-1476] Add API tags to request timeout tracking

lib/client.js, spec/client_spec.js
:v:
Removes arguments from the action tags captured for `sdk_request_timeout` events, reducing the likelihood of unbounded custom metrics being sent to Datadog.
See: https://zendesk.slack.com/archives/C1230V1CG/p1550706092011000?thread_ts=1550706075.010600&cid=C1230V1CG.
* JIRA: https://zendesk.atlassian.net/browse/AF-1514
* Low - Datadog tracking for `sdk_request_timeout` fails because of errors in tag strings.
=> [AF-1514] Constrain tags sent to Datadog for SDK request timeout events

lib/client.js, spec/client_spec.js
:v:
Extends the SDK request timeout to 5 minutes, and adds instrumentation to track the time taken to resolve every request longer than 10 seconds.
Measured times are grouped into 10 second ranges to ensure tags sent to Datadog are bounded.
* JIRA: https://zendesk.atlassian.net/browse/AF-1528
* Low - Datadog tracking for `sdk_request_timeout` fails because of errors in tag strings.
=> [AF-1528] Add instrumentation to measure time for SDK request timeouts

.travis.yml, package-lock.json, package.json
:v:
Updates `Karma` to resolve vulnerabilities in the `braces` and `just-extend` packages (dependencies of `Karma`).
Also updates the version of Node on Travis to match the current `.node-version` (v10.13.0).
* Low - Test suite fails because of changes in Karma syntax.
=> Update vulnerable Node dependencies

package-lock.json
:v:
Bump `js-yaml` and `tar` dependencies to address security vulnerabilities reported by Github and `npm audit`.
- `js-yaml` is bumped from `3.12.0` to `3.13.1`
- `tar` is bumped from `4.4.1` to `4.4.8` 
* JIRA: https://zendesk.atlassian.net/browse/AF-1642
* Low. The bumped dependencies are used at development, not runtime (eslint, karma, webpack).
=> Bump dependencies to address security vulnerabilities

.travis.yml, README.md
:v:
Update Fossa command to run `fossa test` as part of Travis check.
- `fossa` is the shorthand for `fossa init` then `fossa analyze`, which only gather information about dependencies of the project then upload that data to Fossa. This command doesn't run further checks or scans.
- `fossa test` triggers the actual scan based on the data provided by `fossa analyze` in the previous step. We only need to run this if `fossa analyze` completed successfully. This step would take a longer time than `analyze` (default timeout is 10 minutes which is unlikely to be hit based on their documentation) and would report exit status back to Travis once it's done.
* JIRA: https://zendesk.atlassian.net/browse/AF-1489
* Slack: …
=> [AF-1489] Update Fossa command

lib/client.js
The regex was insecure as we missed to skip the wildcard character `.`
This would not result in an issue immediately as `ourtescoxcom`(any character in place of that x will do) is not a top level domain available atm, but someone can potentially buy it if they want.
The old regex will match something like this too: https://test.chrisg.ourtescoocom
@zendesk/vegemite 
High. We may break apps for our customers who are using apps on unexpected domains.
=> Fix tesco regex

README.md
This is a simple url documentation change since the ZAF link provided was no longer available.
=> Update ZAF documentation url

.github/workflows/actions.yml
Update node setup action so that all builds pass. At the moment node setup fails because Github has deprecated set-env and add-path commands 
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Update node-setup action

package-lock.json, package.json
Webpack is not a code dependency, its a dev dependency. So moving it where it belongs, else snyk treats it as a code dependency.
Moving to dev dependency does not change anything in the bundle. I have verified it
```
➜  zendesk_app_framework_sdk git:(master) cmp --silent ../cmp-sdk/zaf_sdk-dev.js ../cmp-sdk/zaf_sdk.js && echo '### SUCCESS: Files Are Identical! ###' || echo '### WARNING: Files Are Different! ###'
```
=> Move webpack to dev deps, update snyk to resolve vuln noise

package.json
:v:
Bump the correct version. https://github.com/zendesk/zendesk_app_framework_sdk/commit/f072478129d5544e8b9c19d9ae31f04158421381 was pushed by accident.
* JIRA: https://zendesk.atlassian.net/browse/VEG-XXX
- Make sure [Zendesk Apps Framework regression tests](https://zendesk.atlassian.net/wiki/spaces/ENG/pages/641702848/DevQA+process+in+Vegemite#DevQAprocessinVegemite-regression-checks) are passing with this change.
- Add specific DevQA instructions here ....
NOTE: DevQA steps are to be actioned only once code has been reviewed and approved.
* [HIGH | medium | low] Does it work across browsers (including IE!)?
* [HIGH | medium | low] Does it work in the different products (Support, Chat, Connect)?
* [HIGH | medium | low] Are there any performance implications?
* …
=> [VEG-1404] Bump the version for deployment

.github/workflows/actions.yml, test.sh
:v:
Dependencies which pollute the global in javascript can cause conflicts with versions of libraries used by app developers within their apps. Therefore, to mitigate the risk of conflicts, we would like to identify a way to prevent dependencies from being added to ZAF_SDK unintentionally.
* JIRA: https://zendesk.atlassian.net/browse/VEG-1466
* [low] We just changing the GA to prevent adding dependancies
=> Add package guard GA

.github/workflows/actions.yml
:v:
Dependencies which pollute the global in javascript can cause conflicts with versions of libraries used by app developers within their apps. Therefore, to mitigate the risk of conflicts, we would like to identify a way to prevent dependencies from being added to ZAF_SDK unintentionally.
* JIRA: https://zendesk.atlassian.net/browse/VEG-1466
* [low] We just changing the GA to prevent adding dependancies
=> Check add GA to prevent adding dependencies to package.json

lib/client.js
:v:
This PR contains whitelisting scooter domain to the allow list.
* JIRA: https://zendesk.atlassian.net/browse/VEG-XXX
- Make sure [Zendesk Apps Framework regression tests](https://zendesk.atlassian.net/wiki/spaces/ENG/pages/641702848/DevQA+process+in+Vegemite#DevQAprocessinVegemite-regression-checks) are passing with this change.
- Add specific DevQA instructions here ....
NOTE: DevQA steps are to be actioned only once code has been reviewed and approved.
* [HIGH | medium | low] Does it work across browsers (including IE!)?
* [HIGH | medium | low] Does it work in the different products (Support, Chat, Connect)?
* [HIGH | medium | low] Are there any performance implications?
* [HIGH | medium | low] Any security risks?
* [HIGH | medium | low] What features does this …
=> chore: add zendesk-dev.com domain to allow for scooter

package-lock.json, package.json
:v:
Describe the original problem and the changes made on this PR.
According to this [PR](https://github.com/zendesk/zendesk_app_framework_sdk/commit/01279ad3fffb7d90d4a93d5171af2d5999864ad9#diff-1fb26bc12ac780c7ad7325730ed09fc4c2c3d757c276c3dacc44bfe20faf166f), `uglifyjs-webpack-plugin` has been replaced by `terser-webpack-plugin` and has been no longer used any more. 
Now `uglifyjs-webpack-plugin` is causing following errors when run `npm install` because of it's UglifyJS does not work with webpack v5. 
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: uglifyjs-webpack-plugin@2.2.0
npm ERR! Found: webpack@5.51.1
npm ERR! node_modules/webpack
npm ERR!   peer webpack@"4.x.x || 5.x.x" from @webpack-cli/configtest@1.0.4 …
```
=> [VEG-2362]: Remove unused uglifyjs-webpack-plugin

.github/workflows/release.yml
:v:
enable manual pre-release
* JIRA: https://zendesk.atlassian.net/browse/VEG-2717
- Make sure [Zendesk Apps Framework regression tests](https://zendesk.atlassian.net/wiki/spaces/ENG/pages/641702848/DevQA+process+in+Vegemite#DevQAprocessinVegemite-regression-checks) are passing with this change.
- Add specific DevQA instructions here ....
NOTE: DevQA steps are to be actioned only once code has been reviewed and approved.
* Low: ci changes only
=> ci: enable manual pre-release

DEPLOY.md
:v:
/cc @zendesk/vegemite @zendesk/wattle
As per this [re-org announcement](https://zendesk.slack.com/archives/C082LS1HM3M/p1732659075201119), Wattle is taking ownership of ZAF/ZCLI and related projects. This PR updates the repo to reflect those changes.
* [low] Just a doc change
=> Replace vegemite references to wattle

package-lock.json
:v:
/cc @zendesk/wattle 
Fix CVE-2021-3807, CVE-2022-37601 and CVE-2022-37601.
* JIRA: https://zendesk.atlassian.net/browse/APPS-7391
* [low] What features does this touch? Update development packages.
=> [APPS-7391] Dedupe and update packages to fix vulnerabilities
